// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bright': string;
  'footer': string;
  'matrixCeil': string;
  'matrixRow': string;
  'part': string;
  'sidebarRow': string;
  'sum': string;
}
export const cssExports: CssExports;
export default cssExports;
