// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bright': string;
  'footer': string;
  'matrixCeil': string;
  'part': string;
}
export const cssExports: CssExports;
export default cssExports;
