// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form_params': string;
  'inputField': string;
}
export const cssExports: CssExports;
export default cssExports;
