// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'matrixContent': string;
  'matrixHeader': string;
  'matrixWrap': string;
}
export const cssExports: CssExports;
export default cssExports;
